/**
 * Sample Data untuk Mockup Sistem Kuesioner Keluarga Sehat (KS)
 * Data ini mencerminkan kondisi riil di Indonesia
 */

export const sampleProvinsi = [
  "DKI Jakarta",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Banten",
  "Sumatera Utara",
  "Sulawesi Selatan",
];

export const sampleKabupatenKota = {
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Utara",
    "Jakarta Selatan",
    "Jakarta Barat",
    "Jakarta Timur",
  ],
  "Jawa Barat": [
    "Kota Bandung",
    "Kota Bekasi",
    "Kota Bogor",
    "Kabupaten Bandung",
    "Kabupaten Bogor",
  ],
};

export const sampleKecamatan = [
  "Menteng",
  "Tanah Abang",
  "Kelapa Gading",
  "Cilandak",
  "Kebayoran Baru",
  "Coblong",
  "Cicendo",
];

export const samplePuskesmas = [
  { nama: "Puskesmas Menteng", kode: "PKM-MEN-001" },
  { nama: "Puskesmas Tanah Abang", kode: "PKM-TAB-002" },
  { nama: "Puskesmas Kelapa Gading", kode: "PKM-KEL-003" },
  { nama: "Puskesmas Cilandak", kode: "PKM-CIL-004" },
  { nama: "Puskesmas Kebayoran", kode: "PKM-KEB-005" },
];

export const sampleDesaKelurahan = [
  "Gondangdia",
  "Kebon Sirih",
  "Menteng",
  "Kelapa Gading Barat",
  "Kelapa Gading Timur",
  "Cilandak Barat",
  "Cipete Selatan",
];

// Sample 5 Keluarga dengan Data Lengkap
export const sampleKeluarga = [
  {
    // Keluarga 1: Keluarga Muda dengan Balita
    questionnaire: {
      provinsi: "DKI Jakarta",
      kabupatenKota: "Jakarta Selatan",
      kecamatan: "Cilandak",
      namaPuskesmas: "Puskesmas Cilandak",
      kodePuskesmas: "PKM-CIL-004",
      desaKelurahan: "Cilandak Barat",
      rw: "05",
      rt: "03",
      noUrutBangunan: "12",
      noUrutKeluarga: "001",
      alamatRumah: "Jl. Cilandak Tengah No. 12",
      namaKepalaKeluarga: "Ahmad Rizki",
      saranaAirBersih: "YA",
      jenisAirMinum: "PDAM",
      jambanKeluarga: "YA",
      jenisJamban: "Kloset duduk dengan leher angsa",
      gangguanJiwaBerat: "TIDAK",
      obatGangguanJiwa: "TIDAK",
      anggotaDipasungi: "TIDAK",
      namaPengumpulData: "Siti Nurhaliza",
      namaSupervisor: "Dr. Bambang Sutejo",
      tanggalPengumpulan: new Date("2025-10-15"),
    },
    anggotaKeluarga: [
      {
        nama: "Ahmad Rizki",
        hubunganKeluarga: "KEPALA_KELUARGA",
        tanggalLahir: new Date("1990-05-15"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Kawin",
        agama: "Islam",
        pendidikan: "S1",
        pekerjaan: "Karyawan Swasta",
        nik: "3174051505900001",
        // Gangguan Kesehatan
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 120,
        diastolik: 80,
      },
      {
        nama: "Dewi Anggraini",
        hubunganKeluarga: "ISTRI_SUAMI",
        tanggalLahir: new Date("1992-08-20"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Kawin",
        sedangHamil: "TIDAK",
        agama: "Islam",
        pendidikan: "S1",
        pekerjaan: "Guru",
        nik: "3174052008920002",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        kontrasepsiKB: "YA",
        pengukuranTekananDarah: "YA",
        sistolik: 115,
        diastolik: 75,
      },
      {
        nama: "Raka Aditya",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("2022-03-10"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Belum Kawin",
        agama: "Islam",
        nik: "3174051003220003",
        kartuJKN: "YA",
        merokok: "TIDAK",
        pemantauanPertumbuhanBalita: "YA",
        imunisasiLengkap: "YA",
      },
      {
        nama: "Zahra Putri",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("2024-06-15"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Belum Kawin",
        agama: "Islam",
        nik: "3174051506240004",
        kartuJKN: "YA",
        asiEksklusif: "YA",
      },
    ],
  },

  {
    // Keluarga 2: Keluarga dengan Lansia
    questionnaire: {
      provinsi: "DKI Jakarta",
      kabupatenKota: "Jakarta Pusat",
      kecamatan: "Menteng",
      namaPuskesmas: "Puskesmas Menteng",
      kodePuskesmas: "PKM-MEN-001",
      desaKelurahan: "Gondangdia",
      rw: "08",
      rt: "05",
      noUrutBangunan: "45",
      noUrutKeluarga: "002",
      alamatRumah: "Jl. Gondangdia Lama No. 45",
      namaKepalaKeluarga: "Budi Santoso",
      saranaAirBersih: "YA",
      jenisAirMinum: "PDAM",
      jambanKeluarga: "YA",
      jenisJamban: "Kloset jongkok dengan leher angsa",
      gangguanJiwaBerat: "TIDAK",
      obatGangguanJiwa: "TIDAK",
      anggotaDipasungi: "TIDAK",
      namaPengumpulData: "Rina Marlina",
      namaSupervisor: "Dr. Susi Susanti",
      tanggalPengumpulan: new Date("2025-10-18"),
    },
    anggotaKeluarga: [
      {
        nama: "Budi Santoso",
        hubunganKeluarga: "KEPALA_KELUARGA",
        tanggalLahir: new Date("1965-12-10"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Kawin",
        agama: "Kristen",
        pendidikan: "SMA",
        pekerjaan: "Pensiunan PNS",
        nik: "3171021012650001",
        kartuJKN: "YA",
        merokok: "YA",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "YA",
        obatHipertensiTeratur: "YA",
        pengukuranTekananDarah: "YA",
        sistolik: 140,
        diastolik: 90,
      },
      {
        nama: "Sri Wahyuni",
        hubunganKeluarga: "ISTRI_SUAMI",
        tanggalLahir: new Date("1968-03-22"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Kawin",
        agama: "Kristen",
        pendidikan: "SMA",
        pekerjaan: "Ibu Rumah Tangga",
        nik: "3171022203680002",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "YA",
        obatHipertensiTeratur: "YA",
        pengukuranTekananDarah: "YA",
        sistolik: 145,
        diastolik: 92,
      },
      {
        nama: "Hendra Wijaya",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("1995-07-18"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Belum Kawin",
        agama: "Kristen",
        pendidikan: "S1",
        pekerjaan: "Marketing",
        nik: "3171021807950003",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 118,
        diastolik: 78,
      },
    ],
  },

  {
    // Keluarga 3: Keluarga dengan Ibu Hamil
    questionnaire: {
      provinsi: "DKI Jakarta",
      kabupatenKota: "Jakarta Utara",
      kecamatan: "Kelapa Gading",
      namaPuskesmas: "Puskesmas Kelapa Gading",
      kodePuskesmas: "PKM-KEL-003",
      desaKelurahan: "Kelapa Gading Barat",
      rw: "12",
      rt: "07",
      noUrutBangunan: "28",
      noUrutKeluarga: "003",
      alamatRumah: "Jl. Boulevard Raya No. 28",
      namaKepalaKeluarga: "Eko Prasetyo",
      saranaAirBersih: "YA",
      jenisAirMinum: "PDAM",
      jambanKeluarga: "YA",
      jenisJamban: "Kloset duduk dengan leher angsa",
      gangguanJiwaBerat: "TIDAK",
      obatGangguanJiwa: "TIDAK",
      anggotaDipasungi: "TIDAK",
      namaPengumpulData: "Lina Anggraeni",
      namaSupervisor: "Dr. Hendra Kusuma",
      tanggalPengumpulan: new Date("2025-10-20"),
    },
    anggotaKeluarga: [
      {
        nama: "Eko Prasetyo",
        hubunganKeluarga: "KEPALA_KELUARGA",
        tanggalLahir: new Date("1988-11-05"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Kawin",
        agama: "Islam",
        pendidikan: "S2",
        pekerjaan: "Manager",
        nik: "3175010511880001",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 125,
        diastolik: 82,
      },
      {
        nama: "Fitri Handayani",
        hubunganKeluarga: "ISTRI_SUAMI",
        tanggalLahir: new Date("1990-02-14"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Kawin",
        sedangHamil: "YA",
        agama: "Islam",
        pendidikan: "S1",
        pekerjaan: "Ibu Rumah Tangga",
        nik: "3175011402900002",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        kontrasepsiKB: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 110,
        diastolik: 70,
      },
      {
        nama: "Alya Putri",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("2020-09-25"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Belum Kawin",
        agama: "Islam",
        nik: "3175012509200003",
        kartuJKN: "YA",
        merokok: "TIDAK",
        pemantauanPertumbuhanBalita: "YA",
        imunisasiLengkap: "YA",
      },
    ],
  },

  {
    // Keluarga 4: Keluarga dengan Riwayat TB
    questionnaire: {
      provinsi: "DKI Jakarta",
      kabupatenKota: "Jakarta Barat",
      kecamatan: "Tanah Abang",
      namaPuskesmas: "Puskesmas Tanah Abang",
      kodePuskesmas: "PKM-TAB-002",
      desaKelurahan: "Kebon Sirih",
      rw: "03",
      rt: "02",
      noUrutBangunan: "67",
      noUrutKeluarga: "004",
      alamatRumah: "Jl. Tanah Abang III No. 67",
      namaKepalaKeluarga: "Darmawan",
      saranaAirBersih: "YA",
      jenisAirMinum: "Sumur",
      jambanKeluarga: "YA",
      jenisJamban: "Kloset jongkok dengan leher angsa",
      gangguanJiwaBerat: "TIDAK",
      obatGangguanJiwa: "TIDAK",
      anggotaDipasungi: "TIDAK",
      namaPengumpulData: "Andi Wijaya",
      namaSupervisor: "Dr. Maria Ulfa",
      tanggalPengumpulan: new Date("2025-10-22"),
    },
    anggotaKeluarga: [
      {
        nama: "Darmawan",
        hubunganKeluarga: "KEPALA_KELUARGA",
        tanggalLahir: new Date("1978-04-08"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Kawin",
        agama: "Islam",
        pendidikan: "SMP",
        pekerjaan: "Wiraswasta",
        nik: "3173040804780001",
        kartuJKN: "YA",
        merokok: "YA",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "YA",
        obatTBC6Bulan: "YA",
        batukDarah2Minggu: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 130,
        diastolik: 85,
      },
      {
        nama: "Sumiati",
        hubunganKeluarga: "ISTRI_SUAMI",
        tanggalLahir: new Date("1980-06-12"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Kawin",
        agama: "Islam",
        pendidikan: "SMP",
        pekerjaan: "Pedagang",
        nik: "3173041206800002",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        kontrasepsiKB: "YA",
        pengukuranTekananDarah: "YA",
        sistolik: 118,
        diastolik: 76,
      },
      {
        nama: "Andi Pratama",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("2005-01-20"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Belum Kawin",
        agama: "Islam",
        pendidikan: "SMA",
        pekerjaan: "Pelajar",
        nik: "3173042001050003",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 115,
        diastolik: 75,
      },
      {
        nama: "Siti Nurhaliza",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("2010-08-15"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Belum Kawin",
        agama: "Islam",
        pendidikan: "SMP",
        pekerjaan: "Pelajar",
        nik: "3173041508100004",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
      },
    ],
  },

  {
    // Keluarga 5: Keluarga Besar dengan Gangguan Jiwa
    questionnaire: {
      provinsi: "DKI Jakarta",
      kabupatenKota: "Jakarta Selatan",
      kecamatan: "Kebayoran Baru",
      namaPuskesmas: "Puskesmas Kebayoran",
      kodePuskesmas: "PKM-KEB-005",
      desaKelurahan: "Cipete Selatan",
      rw: "06",
      rt: "04",
      noUrutBangunan: "89",
      noUrutKeluarga: "005",
      alamatRumah: "Jl. Cipete Raya No. 89",
      namaKepalaKeluarga: "Hadi Purnomo",
      saranaAirBersih: "YA",
      jenisAirMinum: "PDAM",
      jambanKeluarga: "YA",
      jenisJamban: "Kloset duduk dengan leher angsa",
      gangguanJiwaBerat: "YA",
      obatGangguanJiwa: "YA",
      anggotaDipasungi: "TIDAK",
      namaPengumpulData: "Budi Hartono",
      namaSupervisor: "Dr. Ani Wijaya",
      tanggalPengumpulan: new Date("2025-10-25"),
    },
    anggotaKeluarga: [
      {
        nama: "Hadi Purnomo",
        hubunganKeluarga: "KEPALA_KELUARGA",
        tanggalLahir: new Date("1970-09-15"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Kawin",
        agama: "Islam",
        pendidikan: "S1",
        pekerjaan: "PNS",
        nik: "3174051509700001",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "YA",
        obatHipertensiTeratur: "YA",
        pengukuranTekananDarah: "YA",
        sistolik: 138,
        diastolik: 88,
      },
      {
        nama: "Ratna Sari",
        hubunganKeluarga: "ISTRI_SUAMI",
        tanggalLahir: new Date("1972-11-20"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Kawin",
        agama: "Islam",
        pendidikan: "S1",
        pekerjaan: "Guru",
        nik: "3174052011720002",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        kontrasepsiKB: "YA",
        pengukuranTekananDarah: "YA",
        sistolik: 122,
        diastolik: 80,
      },
      {
        nama: "Rudi Hermawan",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("1998-03-10"),
        jenisKelamin: "PRIA",
        statusPerkawinan: "Belum Kawin",
        agama: "Islam",
        pendidikan: "SMA",
        pekerjaan: "Tidak Bekerja",
        nik: "3174051003980003",
        kartuJKN: "YA",
        merokok: "YA",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 120,
        diastolik: 78,
      },
      {
        nama: "Maya Sari",
        hubunganKeluarga: "ANAK",
        tanggalLahir: new Date("2002-05-25"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Belum Kawin",
        agama: "Islam",
        pendidikan: "S1",
        pekerjaan: "Mahasiswa",
        nik: "3174052505020004",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "TIDAK",
        kontrasepsiKB: "TIDAK",
        pengukuranTekananDarah: "YA",
        sistolik: 110,
        diastolik: 72,
      },
      {
        nama: "Wati Purnomo",
        hubunganKeluarga: "ORANG_TUA",
        tanggalLahir: new Date("1945-02-10"),
        jenisKelamin: "WANITA",
        statusPerkawinan: "Janda",
        agama: "Islam",
        pendidikan: "SD",
        pekerjaan: "Tidak Bekerja",
        nik: "3174051002450005",
        kartuJKN: "YA",
        merokok: "TIDAK",
        buangAirBesarJamban: "YA",
        airBersih: "YA",
        diagnosisTB: "TIDAK",
        diagnosisHipertensi: "YA",
        obatHipertensiTeratur: "YA",
        pengukuranTekananDarah: "YA",
        sistolik: 150,
        diastolik: 95,
      },
    ],
  },
];

// Data Pengumpul Data / Enumerator
export const sampleEnumerator = [
  { nama: "Siti Nurhaliza", nik: "3174051234567890" },
  { nama: "Rina Marlina", nik: "3171021234567891" },
  { nama: "Lina Anggraeni", nik: "3175011234567892" },
  { nama: "Andi Wijaya", nik: "3173041234567893" },
  { nama: "Budi Hartono", nik: "3174051234567894" },
];

// Data Supervisor
export const sampleSupervisor = [
  { nama: "Dr. Bambang Sutejo", nip: "197001011998031001" },
  { nama: "Dr. Susi Susanti", nip: "197205152000032002" },
  { nama: "Dr. Hendra Kusuma", nip: "196808201995121003" },
  { nama: "Dr. Maria Ulfa", nip: "197512102001122004" },
  { nama: "Dr. Ani Wijaya", nip: "198003252005012005" },
];

// Summary Statistics untuk Dashboard
export const mockDashboardStats = {
  totalKuesioner: 247,
  totalKeluarga: 247,
  totalAnggotaKeluarga: 1042,
  kuesionerBulanIni: 45,
  statusDistribution: {
    DRAFT: 12,
    IN_PROGRESS: 8,
    COMPLETED: 180,
    SUBMITTED: 35,
    VERIFIED: 12,
  },
  provinsiDistribution: {
    "DKI Jakarta": 150,
    "Jawa Barat": 45,
    "Jawa Tengah": 28,
    "Jawa Timur": 15,
    Banten: 9,
  },
  kesehatanStats: {
    kepemilikanJKN: 945, // 90.7% dari 1042
    hipertensi: 87, // 8.3%
    tuberkulosis: 12, // 1.2%
    gangguanJiwa: 5, // 0.5%
    balitaImunisasi: 156, // dari 172 balita (90.7%)
    ibuHamil: 23,
    penggunaKB: 198, // dari 412 wanita usia 10-54
  },
};

// Helper function untuk generate random date dalam range
export function randomDateBetween(start: Date, end: Date): Date {
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  );
}

// Helper untuk generate NIK random
export function generateNIK(
  provinsi: string,
  kabupaten: string,
  tanggalLahir: Date
): string {
  const kodeProvinsi = "31"; // DKI Jakarta
  const kodeKabupaten = "74"; // Jakarta Selatan
  const tgl = tanggalLahir.getDate().toString().padStart(2, "0");
  const bln = (tanggalLahir.getMonth() + 1).toString().padStart(2, "0");
  const thn = tanggalLahir.getFullYear().toString().slice(-2);
  const random = Math.floor(Math.random() * 10000)
    .toString()
    .padStart(4, "0");

  return `${kodeProvinsi}${kodeKabupaten}${tgl}${bln}${thn}${random}`;
}
